import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import referralsRouter from "./referrals.js";
import balancesRouter from "./balances.js";
import withdrawalsRouter from "./withdrawals.js";
import tasksRouter from "./tasks.js";
import configRouter from "./config.js";
import swychrRouter from "./swychr.js";
import missionsRouter from "./missions.js";
import contactRouter from "./contact.js";
import storageRouter from "./storage.js";
import activitiesRouter from "./activities.js";
import activityWithdrawalsRouter from "./activityWithdrawals.js";
import activitySchedulesRouter from "./activitySchedules.js";
import adminRouter from "./admin.js";
import contactsRouter from "./contacts.js";
import formationsProRouter from "./formationsPro.js";
import formationsRouter from "./formations.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(referralsRouter);
router.use(balancesRouter);
router.use(withdrawalsRouter);
router.use(tasksRouter);
router.use(configRouter);
router.use(swychrRouter);
router.use(missionsRouter);
router.use(contactRouter);
router.use(storageRouter);
router.use(activitiesRouter);
router.use(activityWithdrawalsRouter);
router.use(activitySchedulesRouter);
router.use(adminRouter);
router.use(contactsRouter);
router.use(formationsProRouter);
router.use(formationsRouter);

export default router;
